apiVersion: apps/v1
kind: Deployment
## Describe the deployment
metadata:
  name: auth-depl
## Mention the specs and find it when it is running.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
## Describes how to create each individual pod
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: us.gcr.io/ticketing-dev-406516/auth
          image: st/auth
---
## To communicate with auth pod, we are creating this service which does the communication
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
## Describes what pods to create the service for and how to communicate with it as pods are ephemeral.
spec:
  ## Default is clusterIP service
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
