apiVersion: apps/v1
kind: Deployment
## Describe the deployment
metadata:
  name: client-depl
## Mention the specs and find it when it is running.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
## Describes how to create each individual pod
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          # image: us.gcr.io/ticketing-dev-406516/auth
          image: st-frontend

---
## To communicate with auth pod, we are creating this service which does the communication
apiVersion: v1
kind: Service
metadata:
  name: client-srv
## Describes what pods to create the service for and how to communicate with it as pods are ephemeral.
spec:
  ## Default is clusterIP service
  selector:
    app: client
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
